#!/bin/sh
# Should be run as user www-data, perhaps as so:
# sudo su www-data ./oolaunch
cd /tmp
Xvfb :1 -screen 0 1024x768x24 &
OOWRITER=oowriter
echo $OOWRITER

$OOWRITER -headless "-accept=socket,host=localhost,port=2002;urp;" -display :1.0 &
